  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v1.0
        env:
          BROWSER: chrome
          ROBOT_TESTS_DIR: ${{ github.workspace }}/ExemploSelenium
          ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports