name: robot_test
on: [push]
jobs:
  run_robot_framework_selenium_tests_by_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Run Robot Framework API Tests
        using: 'docker'
        image: 'Dockerfile'
        run: robot -d ${{ github.workspace }}/results ${{ github.workspace }}/ExemploAPI_ServeRest/Exemplo_API_ServeRest.robot
      - name: Upload Tests Results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/results