name: robot_tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: Dockerfile
    steps:
      - name: Run Robot Framework API Tests        
        run: robot -d ${{ github.workspace }}/results ${{ github.workspace }}/ExemploAPI_ServeRest/Exemplo_API_ServeRest.robot
      - name: Upload Tests Results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/results