name: Robot Framework Tests

on: [push]

jobs:

  api_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/ExemploAPI_ServeRest/requirements.txt
      - name: Run Robot Framework API Tests
        run: |
          robot -d ${{ github.workspace }}/ExemploAPI_ServeRest/results ${{ github.workspace }}/ExemploAPI_ServeRest
      - name: Upload Tests Results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/ExemploAPI_ServeRest/results

  browser_test:
    runs-on: ubuntu-latest
    container:
      image: marketsquare/robotframework-browser:latest
    steps:
      - name: Run Robot Framework Web Tests with Library Browser
        run: |
          robot -d ${{ github.workspace }}/ExemploBrowser/results --ipc=host --security-opt seccomp=seccomp_profile.json ${{ github.workspace }}/ExemploBrowser
      - name: Upload Tests Results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: ${{ github.workspace }}/ExemploBrowser/results